### ISSUE TITLE
SvelteCliSample error: Package subpath './compiler.js' is not defined by "exports"

### ISSUE THREAD

**Issue by robertovanoli** [Kiho/aspcore-spa-cli#22]
Hello Kiho, thankyou for this repo. 

I'm trying to use it for my purposes and I have an error. It is fired just after clonig repo and running project SvelteCliSample from visualstudio (non modification at sample code yet).  The same error if i run "npm run dev" from console.

do you have any advice? thank you R

`Error: Package subpath './compiler.js' is not defined by "exports" in C:\Git\Svelte Templates\Kiho\aspcore-spa-cli\samples\SvelteCliSample\ClientApp\node_modules\svelte\package.json`

![Cattura](https://user-images.githubusercontent.com/17762203/214253481-05d97639-e717-4358-9bb3-e14ae895d68d.PNG)
![Cattura1](https://user-images.githubusercontent.com/17762203/214253491-b2121128-48f5-4e2c-9469-0635b5210733.PNG)

**Comment by robertovanoli** [comment]
updating to the most recent versions as suggested [here ](https://stackoverflow.com/questions/66965954/build-error-after-updating-svelte-package-subpath-compiler-js-is-not-define) does not solve

```
{
  "devDependencies": {
    "rollup-plugin-svelte": "^6.1.1"
  },
  "dependencies": {
    "svelte": "^3.55.1"
  }
}
```

**Comment by Kiho** [comment]
I updated sample app, please try and let me know if you still facing issues.

**Comment by robertovanoli** [comment]
yes ! its working fine now thankyou  R
