### ISSUE TITLE
404 in production

### ISSUE THREAD

**Issue by moalamri** [Kiho/aspcore-spa-cli#6]
I'm always getting 404 error when I deploy for production environment.
I've removed `MapToSpaCliProxy` from endpoints. 
Also used `UseSpaStaticFiles()`, but still the same issue.

**Comment by moalamri** [comment]
Same issues with both examples:
https://github.com/Kiho/aspcore-spa-cli/tree/master/samples/SvelteCliSample
https://github.com/Kiho/aspcore-spa-cli/tree/master/samples/SviteSample

**Comment by Kiho** [comment]
I found issue with SviteSample in production and fixed it https://github.com/Kiho/aspcore-spa-cli/blob/master/samples/SviteSample/Startup.cs#L61
NPM script should be invoked only in dev mode,  but Svelte example should work as is.

**Comment by moalamri** [comment]
Thank you so much, that did fix the issue.
