### ISSUE TITLE
use vite-plugin-svelte instead of svite

### ISSUE THREAD

**Issue by moalamri** [Kiho/aspcore-spa-cli#7]
Hi,
According to Svite creator the package is discontinued and no longer supported. 
It has been migrated to [vite-plugin-svelte](https://github.com/sveltejs/vite-plugin-svelte) based on new vite2.
Can you please apply the migration to Svite example?
Thank you.

**Comment by moalamri** [comment]
Working great. Thank you..

**Comment by Kiho** [comment]
Good to hear.
